spring:
    profiles:
        active: dev
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: "010215"
        url: jdbc:mysql://localhost:3306/im_core?useSSL=false&serverTimezone=Asia/Shanghai
        username: root
#    ????
    main:
        allow-circular-references: true
    mvc:
    servlet:
        multipart:
            max-file-size: 10MB  		# 设置单个文件最大大小为10MB
            max-request-size: 100MB  	# 设置多个文件大小为100MB
    jackson:
        time-zone: GMT+8

appConfig:
    appId: 10000
    privateKey: 123456
    zkAddr: 127.0.0.1:2181
    zkConnectTimeOut: 5000
    imRouteWay: 3  # 路由策略  1:随机 2: 轮询 3:hash
    consistentHashWay: 1  # 一致性hash算法具体的hash算法  1:TreeMap 2: 其他自定义
    sendMessageCheckFriend: true #发送消息是否校验关系链
    sendMessageCheckBlack: true #发送消息是否校验黑名单
    callbackUrl: http://127.0.0.1:8080/callback
    modifyUserAfterCallback: false # 用户资料变更之后回调开关
    addFriendAfterCallback: false # 添加好友之后回调开关
    addFriendBeforeCallback: false # 添加好友之前回调开关
    modifyFriendAfterCallback: false # 修改好友之后回调开关
    deleteFriendAfterCallback: false # 删除好友之后回调开关
    addFriendShipBlackAfterCallback: false #添加黑名单之后回调开关
    deleteFriendShipBlackAfterCallback: false #删除黑名单之后回调开关
    createGroupAfterCallback: false # 创建群聊之后回调开关
    modifyGroupAfterCallback: false # 修改群聊之后回调开关
    destroyGroupAfterCallback: false # 解散群聊之后回调开关
    deleteGroupMemberAfterCallback: false # 删除群成员之后回调
    addGroupMemberAfterCallback: false # 拉人入群之后回调
    addGroupMemberBeforeCallback: false # 拉人入群之前回调
    sendMessageAfterCallback: false # 发送单聊消息之后
    sendMessageBeforeCallback: false # 发送单聊消息之前
    sendGroupMessageAfterCallback: false # 发送群聊消息之后
    sendGroupMessageBeforeCallback: false # 发送群聊消息之前
    offlineMessageCount: 1000 #离线消息存储条数
    deleteConversationSyncMode: 1 #1多段同步
    user:
        logoUploadPath: "D:\\study\\GraduationDesign\\im-chat-master\\chat-room-vue\\src\\assets\\img\\userLogo"
        logoAdminPath: "D:\\study\\GraduationDesign\\im-chat-master\\im-chat-admin\\src\\assets\\img\\userLogo"
        logoPath: "\\src\\assets\\img\\userLogo\\"
    group:
        logoUploadPath: "D:\\study\\GraduationDesign\\im-chat-master\\chat-room-vue\\src\\assets\\img\\groupLogo"
        logoAdminPath: "D:\\study\\GraduationDesign\\im-chat-master\\im-chat-admin\\src\\assets\\img\\groupLogo"
        logoPath: "\\src\\assets\\img\\groupLogo\\"
    data:
        uploadPath: "D:\\study\\GraduationDesign\\im-chat-master\\chat-room-vue\\src\\assets\\img\\data"
        adminPath: "D:\\study\\GraduationDesign\\im-chat-master\\im-chat-admin\\src\\assets\\img\\data"
        path: "\\src\\assets\\img\\data\\"
        downloadPath: "D:\\im-chat\\"

    redis:
        host: 127.0.0.1
        port: 6379
        jedis:
            pool:
                max-active: 100
                max-idle: 100
                max-wait: 1000
                min-idle: 10
    rabbitmq:
        host: localhost
        port: 5672
        addresses: localhost
        username: guest
        password: guest
        # 设置监听为手动应答模式
        listener:
            simple:
                acknowledge-mode: manual


# logger ??
logging:
    config: classpath:logback-spring.xml

server:
    port: 8080

httpclient:
    maxTotal: 100
    defaultMaxPerRoute: 50
    connectTimeout: 2000
    connectionRequestTimeout: 2000
    socketTimeout: 5000
    staleConnectionCheckEnabled: true
#mybatis-plus:
#    configuration:
#        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



user:
    logoUploadPath: "D:\\study\\GraduationDesign\\im-chat-master\\chat-room-vue\\src\\assets\\img\\userLogo\\"
    logoAdminPath: "D:\\study\\GraduationDesign\\im-chat-master\\im-chat-admin\\src\\assets\\img\\userLogo\\"
    logoPath: "\\src\\assets\\img\\userLogo\\"


group:
    logoUploadPath: "D:\\study\\GraduationDesign\\im-chat-master\\chat-room-vue\\src\\assets\\img\\groupLogo\\"
    logoAdminPath: "D:\\study\\GraduationDesign\\im-chat-master\\im-chat-admin\\src\\assets\\img\\groupLogo\\"
    logoPath: "\\src\\assets\\img\\groupLogo\\"

data:
    uploadPath: "D:\\study\\GraduationDesign\\im-chat-master\\chat-room-vue\\src\\assets\\data\\"
    logoAdminPath: "D:\\study\\GraduationDesign\\im-chat-master\\im-chat-admin\\src\\assets\\data\\"
    path: "\\src\\assets\\data\\"
    downloadPath: "D:\\"
